on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: main
        uses: ./
        with:
          message: 'If You can read this you just got lucky!'
          percentage: 50
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
